### ISSUE TITLE
Produces package shows 5.0.0

### ISSUE THREAD

**Issue by mrwokkel** [keystonejs/create-keystone-app#263]
Is this still correct?
https://github.com/keystonejs/create-keystone-app/blob/d18e3c73b18499895a05ed2d5c0a429619d41c84/create-keystone-app/starter/package.json#L3

**Comment by rickysullivan** [comment]
I came here to find this out for myself. I was testing out v6 and noticed it had generated a package version of 5. Seems strange. You'd think scaffolding out an project for you it would just generate v1.0.0.

**Comment by bladey** [comment]
Excellent point @rickysullivan, we'll revert it to version 1.0.0.

**Comment by bladey** [comment]
Will be reverted in next version - https://github.com/keystonejs/create-keystone-app/pull/272

**Comment by rickysullivan** [comment]
Chur.
