### ISSUE TITLE
Versions outdated, V5 released

### ISSUE THREAD

**Issue by TheRealFlyingCoder** [keystonejs/create-keystone-app#368]
Just dropping this here i'm sure the team are already aware. :)

Updating the create-keystone-app versioning should probably be a release task for any deployments on the keystone repo to make sure no one gets caught on old versions by accident (especially with a major version change).

**Comment by dcousens** [comment]
> Updating the create-keystone-app versioning should probably be a release task for any deployments on the keystone repo to make sure no one gets caught on old versions by accident (especially with a major version change).

@TheRealFlyingCoder yes! I thought about this with the latest release and on seeing @alex-frx be caught out by https://github.com/keystonejs/create-keystone-app/issues/367.

I'll be fixing this momentarily :+1:

**Comment by TheRealFlyingCoder** [comment]
Legend!

I can't comment any ideas for testing... Although i'll point out that you make life a little harder by separating this package into it's own repo.

If you reference some larger solutions they follow similar patterns:

https://github.com/vercel/next.js/
https://github.com/remix-run/remix/

/packages/create-_____

There will usually be a chore task assigned for versioning across each folder in /packages

**Comment by dcousens** [comment]
> Although i'll point out that you make life a little harder by separating this package into it's own repo.

Excellent point, I'm not sure why this was broken out as separate.  I'll see if I can find and post any justification, and if not, well, sounds like that could be an easy win
