### ISSUE TITLE
Unable to create "Tag" before creating "Post"

### ISSUE THREAD

**Issue by tofsjonas** [keystonejs/create-keystone-app#395]
### Reproduce

```bash
yarn create keystone-app
cd my-app
yarn dev
```

1. Go to <http://localhost:3000/>
2. Create Admin User
3.  Go to Posts -> Create Post  **(I missed a step, sorry about that)**
4. Try to add a Tag **_before_** saving the post. Watch it fail

### Expectation

I would expect to be able to create a tag before I save the post

### Screenshots

Nothing to show. It blinks, then It looks like I didn't do anything

### Context

I doubt if it matters, but I'm on node16 and using firefox

**Comment by dcousens** [comment]
> Go to Posts, try to add a Tag before saving the post. Watch it fail

Can you describe what "Watch it fail" represents? What fails?

**Comment by tofsjonas** [comment]
Creating a tag fails 😉

https://user-images.githubusercontent.com/1842179/214245096-b11382e0-999e-48f8-a1a9-50f08b9c51e7.mp4

**Comment by dcousens** [comment]
Thanks for the video @tofsjonas, it helps :yellow_heart:

**Comment by borisno2** [comment]
Hi @tofsjonas
This issue has been resolved in PR https://github.com/keystonejs/keystone/pull/8177 - so will be fixed in the next release of Keystone.

**Comment by borisno2** [comment]
Issue resolved in https://github.com/keystonejs/keystone/releases/tag/2023-02-23
